spring:
  application:
    name: mailing
  mail:
    host: smtp.gmail.com
    port: 587
    username: myGmail@gmail.com
    password: application-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

gmail:
  username: myGmail@gmail.com
  password: application-password